language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements-test.txt
  - pip install coveralls
script: pytest --verbose --cov boom --cov-report term-missing --color yes
after_success: coveralls
